### ISSUE TITLE
Back press on device has no effect.

### ISSUE THREAD

**Issue by RowanG1** [mcatta/android-compose-template#5] opened 2023-02-04 06:28 UTC
Add back button press support.

**Comment by mcatta** [comment] 2023-02-09 08:41
Do you mean that the back press doesn't work? Can I see your implementation (if it's public) in order to understand better the issue, please?

**Comment by mcatta** [comment] 2023-03-23 08:22
I'm closing it because I can't reproduce the issue

**Closed by mcatta** 2023-03-23 08:22 UTC
